<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'

const props = defineProps<{ resource: 'payroll-rate' | 'billing-rate'; title: string }>()
const items = ref<any[]>([]); const agencyPositions = ref<any[]>([]); const regions = ref<any[]>([])
const form = ref<any>({}); const editing = ref<any>(null); const open = ref(false); const busy = ref(false); const loading = ref(true); const error = ref('')
const moneyFields = [{ key: 'RegularRate', label: 'Regular' }, { key: 'OTRate', label: 'OT' }, { key: 'NightDiffRate', label: 'Night diff' }, { key: 'RestDayRate', label: 'Rest day' }, { key: 'SpecialHolidayRate', label: 'Special holiday' }, { key: 'LegalHolidayRate', label: 'Legal holiday' }, { key: 'SpecialHolidayOTRate', label: 'Special holiday OT' }, { key: 'LegalHolidayOTRate', label: 'Legal holiday OT' }, { key: 'BreakDeduction', label: 'Break deduction' }, { key: 'Allowance', label: 'Allowance' }]
const modalTitle = computed(() => editing.value ? `Edit ${props.title.slice(0, -1)}` : `Add ${props.title.slice(0, -1)}`)
const idKey = computed(() => props.resource === 'payroll-rate' ? 'PayrollRateID' : 'BillingRateID')
function reset(item: any = null) { editing.value = item; form.value = { AgencyPositionID: item?.AgencyPositionID ?? '', RegionID: item?.RegionID ?? '', EffectiveDate: item?.EffectiveDate?.slice?.(0, 10) ?? item?.EffectiveDate ?? '', Status: item?.Status ?? 'Active', ...Object.fromEntries(moneyFields.map(({ key }) => [key, item?.[key] ?? 0])) }; error.value = '' }
async function load() { loading.value = true; try { const r: any = await $fetch(`/api/rates/${props.resource}`); items.value = r.items || []; agencyPositions.value = r.agencyPositions || []; regions.value = r.regions || [] } catch (e: any) { error.value = e.data?.statusMessage || 'Unable to load rates.' } finally { loading.value = false } }
async function save() { busy.value = true; error.value = ''; try { await $fetch(`/api/rates/${props.resource}`, { method: editing.value ? 'PUT' : 'POST', body: editing.value ? { id: editing.value[idKey.value], ...form.value } : form.value }); open.value = false; await load() } catch (e: any) { error.value = e.data?.statusMessage || 'Unable to save rate.' } finally { busy.value = false } }
async function deactivate(item: any) { if (!confirm('Mark this rate as inactive?')) return; try { await $fetch(`/api/rates/${props.resource}`, { method: 'DELETE', body: { id: item[idKey.value] } }); await load() } catch (e: any) { error.value = e.data?.statusMessage || 'Unable to deactivate rate.' } }
const currency = (value: any) => new Intl.NumberFormat('en-PH', { style: 'currency', currency: 'PHP' }).format(Number(value) || 0)
onMounted(load)
</script>
<template><main class="rates-page"><header><div><p>RATES</p><h1>{{ title }}</h1></div><button class="primary" @click="reset(); open = true">+ Add rate</button></header><p v-if="error" class="error">{{ error }}</p><div class="table-wrap"><table><thead><tr><th>Agency position</th><th>Region</th><th>Regular rate</th><th>Effective date</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr v-if="loading"><td colspan="6">Loading…</td></tr><tr v-else-if="!items.length"><td colspan="6">No rates found.</td></tr><tr v-for="item in items" :key="item[idKey]"><td>{{ item.AgencyName }} — {{ item.PositionName }}</td><td>{{ item.RegionName || 'All regions' }}</td><td>{{ currency(item.RegularRate) }}</td><td>{{ item.EffectiveDate || '—' }}</td><td><span class="status" :class="`status--${item.Status.toLowerCase()}`">{{ item.Status }}</span></td><td><button @click="reset(item); open = true">Edit</button><button :disabled="item.Status === 'Inactive'" @click="deactivate(item)">Deactivate</button></td></tr></tbody></table></div><Teleport to="body"><div v-if="open" class="backdrop" @click.self="!busy && (open = false)"><form class="modal" @submit.prevent="save"><button class="close" type="button" @click="open = false">×</button><h2>{{ modalTitle }}</h2><label>Agency position<select v-model="form.AgencyPositionID" required><option value="">Select agency position</option><option v-for="option in agencyPositions" :key="option.AgencyPositionID" :value="option.AgencyPositionID">{{ option.AgencyName }} — {{ option.PositionName }}</option></select></label><label>Region<select v-model="form.RegionID"><option value="">All regions</option><option v-for="option in regions" :key="option.RegionID" :value="option.RegionID">{{ option.RegionCode }} — {{ option.RegionName }}</option></select></label><div class="money-grid"><label v-for="field in moneyFields" :key="field.key">{{ field.label }}<input v-model="form[field.key]" type="number" min="0" step="0.01" /></label></div><label>Effective date<input v-model="form.EffectiveDate" type="date" /></label><label>Status<select v-model="form.Status"><option>Active</option><option>Inactive</option></select></label><p v-if="error" class="error">{{ error }}</p><footer><button type="button" @click="open = false">Cancel</button><button class="primary" :disabled="busy">{{ busy ? 'Saving…' : 'Save rate' }}</button></footer></form></div></Teleport></main></template>
<style scoped>
.rates-page{padding:32px;max-width:1200px;margin:auto;color:#172033;font-family:Inter,system-ui,sans-serif}.rates-page header{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}.rates-page header p{margin:0;color:#5271a5;font-size:.75rem;font-weight:800;letter-spacing:.08em}.rates-page h1{margin:3px 0 0;font-size:1.7rem}.primary{border:0;border-radius:8px;background:#2563eb;color:#fff;padding:10px 15px;font-weight:700;cursor:pointer}.table-wrap{overflow:auto;border:1px solid #dfe5ef;border-radius:10px}table{width:100%;border-collapse:collapse;background:#fff}th,td{padding:13px 14px;text-align:left;border-bottom:1px solid #edf1f6;font-size:.88rem;white-space:nowrap}th{background:#f8fafc;color:#526174;font-size:.75rem;text-transform:uppercase}td button,footer button{border:1px solid #cfd8e6;background:#fff;border-radius:6px;padding:6px 9px;margin-right:6px;cursor:pointer}.status{padding:3px 8px;border-radius:999px;font-size:.74rem;font-weight:700}.status--active{background:#dcfce7;color:#166534}.status--inactive{background:#fee2e2;color:#991b1b}.error{color:#b42318}.backdrop{position:fixed;inset:0;z-index:300;background:rgba(15,23,42,.58);display:grid;place-items:center;padding:16px}.modal{position:relative;width:min(100%,650px);max-height:90vh;overflow:auto;background:#fff;border-radius:12px;padding:26px;display:grid;gap:12px}.modal h2{margin:0}.modal label{display:grid;gap:5px;font-size:.8rem;font-weight:700;color:#475569}.modal input,.modal select{min-height:40px;border:1px solid #cfd8e6;border-radius:7px;padding:8px;font:inherit}.money-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.close{position:absolute;right:12px;top:10px;border:0;background:transparent;font-size:1.5rem;cursor:pointer}.modal footer{display:flex;justify-content:flex-end;margin-top:6px}@media(max-width:600px){.rates-page{padding:20px}.money-grid{grid-template-columns:1fr}}
</style>
