-- Rate updates are separate snapshots. Site links keep their original rate IDs,
-- so every linked site uses the version effective on the work date.
CREATE TABLE IF NOT EXISTS payroll_rate_version (
  PayrollRateVersionID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PayrollRateID INT NOT NULL,
  EffectiveDate DATE NOT NULL,
  RegularRate DECIMAL(10,2) NOT NULL DEFAULT 0,
  OTRate DECIMAL(10,2) NOT NULL DEFAULT 0,
  OTExtRate DECIMAL(10,2) NOT NULL DEFAULT 0,
  NightDiffRate DECIMAL(10,2) NOT NULL DEFAULT 0,
  RestDayRate DECIMAL(10,2) NOT NULL DEFAULT 0,
  RestDayOTRate DECIMAL(10,2) NOT NULL DEFAULT 0,
  SpecialHolidayRate DECIMAL(10,2) NOT NULL DEFAULT 0,
  LegalHolidayRate DECIMAL(10,2) NOT NULL DEFAULT 0,
  SpecialHolidayOTRate DECIMAL(10,2) NOT NULL DEFAULT 0,
  LegalHolidayOTRate DECIMAL(10,2) NOT NULL DEFAULT 0,
  LateDeduction DECIMAL(10,2) NOT NULL DEFAULT 0,
  UndertimeDeduction DECIMAL(10,2) NOT NULL DEFAULT 0,
  BreakDeduction DECIMAL(10,2) NOT NULL DEFAULT 0,
  Allowance DECIMAL(10,2) NOT NULL DEFAULT 0,
  Reason VARCHAR(500) NOT NULL DEFAULT '',
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_payroll_rate_version_date (PayrollRateID, EffectiveDate),
  CONSTRAINT fk_payroll_rate_version_rate FOREIGN KEY (PayrollRateID) REFERENCES payroll_rate (PayrollRateID)
);

CREATE TABLE IF NOT EXISTS billing_rate_version (
  BillingRateVersionID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BillingRateID INT NOT NULL,
  EffectiveDate DATE NOT NULL,
  RegularRate DECIMAL(10,2) NOT NULL DEFAULT 0,
  OTRate DECIMAL(10,2) NOT NULL DEFAULT 0,
  OTExtRate DECIMAL(10,2) NOT NULL DEFAULT 0,
  NightDiffRate DECIMAL(10,2) NOT NULL DEFAULT 0,
  RestDayRate DECIMAL(10,2) NOT NULL DEFAULT 0,
  RestDayOTRate DECIMAL(10,2) NOT NULL DEFAULT 0,
  SpecialHolidayRate DECIMAL(10,2) NOT NULL DEFAULT 0,
  LegalHolidayRate DECIMAL(10,2) NOT NULL DEFAULT 0,
  SpecialHolidayOTRate DECIMAL(10,2) NOT NULL DEFAULT 0,
  LegalHolidayOTRate DECIMAL(10,2) NOT NULL DEFAULT 0,
  LateDeduction DECIMAL(10,2) NOT NULL DEFAULT 0,
  UndertimeDeduction DECIMAL(10,2) NOT NULL DEFAULT 0,
  BreakDeduction DECIMAL(10,2) NOT NULL DEFAULT 0,
  Allowance DECIMAL(10,2) NOT NULL DEFAULT 0,
  Reason VARCHAR(500) NOT NULL DEFAULT '',
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_billing_rate_version_date (BillingRateID, EffectiveDate),
  CONSTRAINT fk_billing_rate_version_rate FOREIGN KEY (BillingRateID) REFERENCES billing_rate (BillingRateID)
);
