-- Prior-period payroll corrections. Attendance stays in its original DTR;
-- approved adjustments are staged for a later payroll cutoff.
CREATE TABLE IF NOT EXISTS payroll_adjustment (
  AdjustmentID INT NOT NULL AUTO_INCREMENT,
  EmployeeID INT NOT NULL,
  SourceBatchID INT NOT NULL,
  TargetBatchID INT NOT NULL,
  AdjustmentType VARCHAR(80) NOT NULL DEFAULT 'Missed Attendance Pay',
  Reason VARCHAR(500) NOT NULL,
  VerificationReference VARCHAR(255) NULL,
  Status ENUM('Draft', 'For Approval', 'Approved', 'Applied', 'Rejected', 'Cancelled') NOT NULL DEFAULT 'Draft',
  TotalAmount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  TargetPayrollID INT NULL,
  Revision INT NOT NULL DEFAULT 1,
  CreatedBy INT NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  SubmittedBy INT NULL,
  SubmittedAt DATETIME NULL,
  ApprovedBy INT NULL,
  ApprovedAt DATETIME NULL,
  AppliedBy INT NULL,
  AppliedAt DATETIME NULL,
  UpdatedBy INT NULL,
  UpdatedAt DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (AdjustmentID),
  KEY idx_payroll_adjustment_employee (EmployeeID, Status),
  KEY idx_payroll_adjustment_source (SourceBatchID),
  KEY idx_payroll_adjustment_target (TargetBatchID, Status),
  KEY idx_payroll_adjustment_payroll (TargetPayrollID),
  CONSTRAINT fk_payroll_adjustment_employee FOREIGN KEY (EmployeeID) REFERENCES employee (EmployeeID) ON UPDATE CASCADE,
  CONSTRAINT fk_payroll_adjustment_source FOREIGN KEY (SourceBatchID) REFERENCES attendance_dtr (BatchID) ON UPDATE CASCADE,
  CONSTRAINT fk_payroll_adjustment_target FOREIGN KEY (TargetBatchID) REFERENCES attendance_dtr (BatchID) ON UPDATE CASCADE,
  CONSTRAINT fk_payroll_adjustment_payroll FOREIGN KEY (TargetPayrollID) REFERENCES payroll (PayrollID) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_payroll_adjustment_createdby FOREIGN KEY (CreatedBy) REFERENCES `user` (UserID) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_payroll_adjustment_submittedby FOREIGN KEY (SubmittedBy) REFERENCES `user` (UserID) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_payroll_adjustment_approvedby FOREIGN KEY (ApprovedBy) REFERENCES `user` (UserID) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_payroll_adjustment_appliedby FOREIGN KEY (AppliedBy) REFERENCES `user` (UserID) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_payroll_adjustment_updatedby FOREIGN KEY (UpdatedBy) REFERENCES `user` (UserID) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT chk_payroll_adjustment_cutoff CHECK (SourceBatchID <> TargetBatchID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payroll_adjustment_line (
  AdjustmentLineID INT NOT NULL AUTO_INCREMENT,
  AdjustmentID INT NOT NULL,
  SourceAttendanceID INT NULL,
  SourceDate DATE NOT NULL,
  ComponentCode VARCHAR(50) NOT NULL,
  Description VARCHAR(150) NOT NULL,
  EntrySource ENUM('DTR Snapshot', 'Manual Verification') NOT NULL DEFAULT 'DTR Snapshot',
  Direction ENUM('Earning', 'Deduction') NOT NULL DEFAULT 'Earning',
  Quantity DECIMAL(8,2) NOT NULL,
  Rate DECIMAL(12,2) NOT NULL,
  Amount DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (AdjustmentLineID),
  UNIQUE KEY uq_payroll_adjustment_source_component (SourceAttendanceID, ComponentCode),
  KEY idx_payroll_adjustment_line_header (AdjustmentID),
  KEY idx_payroll_adjustment_line_date (SourceDate),
  CONSTRAINT fk_payroll_adjustment_line_header FOREIGN KEY (AdjustmentID) REFERENCES payroll_adjustment (AdjustmentID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_payroll_adjustment_line_attendance FOREIGN KEY (SourceAttendanceID) REFERENCES attendance (AttendanceID) ON UPDATE CASCADE,
  CONSTRAINT chk_payroll_adjustment_line_quantity CHECK (Quantity > 0),
  CONSTRAINT chk_payroll_adjustment_line_rate CHECK (Rate >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
